name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload USkript Discord Bot artifact
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: uskript-discord-bot
          path: target/discord-bot.jar